### ISSUE TITLE
Scheduler: Simple

### ISSUE THREAD

**Issue by rustbloom** [Taproot-Manufacturing-Syndicate/hydroponics-controller#1]
We need to turn on the lights and the pump each on their own schedule.

The schedule will be set with a YAML (or maybe a TOML or JSON) file.

The simplest schedule would be:
-lights on at time T0 and off at T1 each day.
-pump runs every X minutes out of every Y minutes.

This is planned to be two async tasks.

Signalling to hardware will be an HTTP request.

**Comment by rustbloom** [comment]
Scope expansion ideas:

- user input from CLI or TUI (probably using the clap crate)
- user-facing readout for current time and upcoming commands (tasks)

**Comment by sigil-03** [comment]
Not sure if it's helpful or not - but a while ago I wrote a little MQTT tool for interfacing with tasmota outlets: 
https://gitlab.com/sigil-03/mqtt-status-rs

**Comment by rustbloom** [comment]
> Not sure if it's helpful or not - but a while ago I wrote a little MQTT tool for interfacing with tasmota outlets: https://gitlab.com/sigil-03/mqtt-status-rs

Maybe @SebKuzminsky could answer this.

The approach has been narrowed to definitely ingesting JSON. Each event will be its own object.
The schedule will be ingested and each device will have a Schedule struct with three fields.
- on: URL
- off: URL
- `Vec<Event>`

An Event will be a timestamp and a bool indicating on or off.

**Comment by rustbloom** [comment]
looks like markup made the `Vec<Event>` above into appearing as just a `Vec`! I'll edit it now.

**Comment by SebKuzminsky** [comment]
I'm looking at the state as of commit 7084ac7b.

It looks like you're really getting comfortable with async!
 
Issues:
* I think we want localtimes, not UTC, for convenience.
* I don't think we want the schedule to be made of absolute times, i think we want time-of-day that applies to any date.  Imagine having to program pump-on and pump-off every two hours for 6 weeks!  I think we can do this pretty conveniently with `chrono::NaiveTime`.

JSON stuff:
* For variables that come from json i suggest using the same names in both places, to reduce brain strain.
* There's a lot of extra structure in the current json schema.  Maybe it's for debugging/learning?  In the final version we want that as lean as possible - no unused layers to the data structure, no extra fields.
* For example, i don't see what the top-level object adds, or the `main` in each device, or really anything but `command`.
* By having a json file with nothing superfluous in it you can make it match the struct in your rs, which lets you `serde_json::from_str()` directly into your struct (instead of into a `serde_json::Value`)

I propose this json, a list of objects where each object has a name, an on-url, off-url, and a list of events:
```
[
    {
        "name": "lights",
        "on": "http://127.0.0.1:9732",
        "off": "http://127.0.0.1:9732",
        "events": [
            {"timestamp": "19:36:00", "on": true},
            {"timestamp": "19:36:05", "on": false},
            {"timestamp": "20:46:10", "on": true},
            {"timestamp": "20:46:15", "on": false}
        ]
    },

    {
        "name": "pump",
        "on": "http://127.0.0.1:9732",
        "off": "http://127.0.0.1:9732",
        "events": [
            {"timestamp": "04:55:05", "on": true},
            {"timestamp": "04:55:15", "on": false}
        ]
    }
]
```

Then the code becomes pretty simple:
```
#[derive(Debug, Deserialize)]
pub struct Schedule {
    name: String,
    on: Url,
    off: Url,
    events: Vec<Event>,
}
  
#[derive(Debug, Deserialize)]
pub struct Event {
    timestamp: NaiveTime,
    on: bool,
}

let schedules: Vec<Schedule> = serde_json::from_str(&schedule_json_str).expect("invalid JSON");
let mut join_set = JoinSet::new();                                                     
for schedule in schedules {                                                               
    join_set.spawn(run_schedule(schedule));
}                                                                                                   
join_set.join_all().await;                                                                          
```

That gives us a `run_schedule()` task for each object in the json array.  `run_schedule()` has just an eternal `loop`.  Inside the loop we iterate over the events, finding the next one, sleeping until it's time, and poking its url.  It'll be like 20 lines total.

**Comment by sigil-03** [comment]
Agree with what @SebKuzminsky said - really good progress here! 

I also think that a more simple config file format will make things easier, and I'd like to emphasize that if done correctly, the entire JSON file can be decomposed into the objects underlying it. 

This section of the code is a little overly complex:
```rust
/* ... */
   let schedule_json_contents: Value = serde_json::from_str(
        &(tokio::fs::read_to_string("schedule.json")
            .await
            .expect("reading in JSON to work")),
    )
    .expect("JSON Value to work after read-in");

    let devices: Value = schedule_json_contents["devices"].clone();

    let mut set: JoinSet<()> = JoinSet::new();

    // parse events and commands, and launch async task in for loop
    for category in devices.as_object().expect("as object to work").keys() {
        let cat = devices
            .get(category)
            .expect("category to be found")
            .as_object()
            .expect("as object to work")
            .keys();

        for fixture in cat {
            // format String to make the call to pointer.
            let commands_path = format!("/{}/{}/commands", category, fixture);
            println!("commands_path {:?}", commands_path);

            // to access the url and event schedule.
            let fixture_schedule: Schedule = serde_json::from_value(
                devices
                    .pointer(&commands_path)
                    .expect("pointer to work")
                    .clone(),
            )
            .expect("serde to get schedule");
/* ... */
```

Since JSON is a hierarchical language, my advice to you would be to try and make your data structures hierarchical as needed (but not overly deep), and then `serde` the entire thing at once into your data structure. This is part of what makes serde so powerful! Instead of having to remember where things are, and hunt through your JSON file - you can pattern your data structures and your JSON file to match. 

Sometimes it can be useful when creating things like this to work backwards - build out your data structures first, and then `Serialize` them into JSON to see what the JSON pattern would look like. 

@SebKuzminsky's suggestion above shows how this method of using `Serde` can condense the entire operation above into a single line, which is awesome :)

**Comment by rustbloom** [comment]
Hi,
Seb and Sigil thanks for the feedback.

I see the call for something much more simple. Seems a likely way forward is a new PR for a new branch and reference to this issue. I like the suggestion to build JSON from the rust code.

To respond to some of the points...
- localtime vs utc : I had originally used DateTime<Local> but it didn't support some transformation I was seeking, at some point during development.
- daily schedule vs date+time : here, and with larger json complexity, the idea to make more complex programs possible, such as running a full grow schedule across months or more. Daily schedules would of course (eventually) be supported, maybe autogenerated with a prompt rather than having to type everything in. Similar ideas for categorizing devices by function and allowing for user-assigned groups.

**Comment by rustflower** [comment]
I've completed a draft incorporating this feedback and I think it is ready for review!

**Comment by rustflower** [comment]
I made a comment on #3 about a possible small improvement.

As it stands the logic just supports devices that have a simple on/off command over HTTP (and right now only using `GET`), but can be extended to any number of devices.
